{% set name = "autots" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed85b511e70d32bfe2230f653c4133c626061b25f24f2d193f49288275e0b070

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.6
    - numpy >=1.14.6
    - pandas >=0.25.*
    - scikit-learn >=0.20.*
    - statsmodels >=0.10.*
    - requests

test:
  imports:
    - autots
    - autots.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/winedarksea/AutoTS
  summary: Automated Time Series Forecasting
  license: MIT
  license_file: LICENSE
  description: |
    AutoTS is a time series package for Python designed for rapidly deploying 
    high-accuracy forecasts at scale.
  doc_url: https://github.com/winedarksea/AutoTS

extra:
  recipe-maintainers:
    - winedarksea
